baseURL = "/"
languageCode = "en-GB"
title = "dotmesh docs"
sectionPagesMenu = "main"

# Highlighting config (Pygments)
pygmentsCodeFences = true

pygmentsOptions = ""
# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsUseClassic = false
pygmentsCodefencesGuessSyntax = true

# See https://help.farbox.com/pygments.html
pygmentsStyle = "monokai"

[params]
  version = "0.0.1 Alpha"

[taxonomies]
  tag = ""
  group = ""
  category = ""

[menu]
    [[menu.main]]
    identifier = "install-setup"
    name       = "Install &amp; setup"
    url        = "/install-setup/"
    synopsis   = "synopsis"
    weight     = 1

    [[menu.main]]
    identifier = "concepts"
    name       = "Concepts"
    url        = "/concepts/"
    synopsis   = "synopsis"
    weight     = 2

    [[menu.main]]
    identifier = "tasks"
    name       = "Tasks"
    url        = "/tasks/"
    synopsis   = "synopsis"
    weight     = 3

    [[menu.main]]
    identifier = "command-references"
    name       = "Command references"
    url        = "/command-references/"
    synopsis   = "synopsis"
    weight     = 4

    [[menu.main]]
    identifier = "release-notes"
    name       = "Release notes"
    url        = "/release-notes/"
    synopsis   = "synopsis"
    weight     = 5

    [[menu.main]]
    identifier = "faq-troubleshooting"
    name       = "FAQ &amp; troubleshooting"
    url        = "/faq-troubleshooting/"
    synopsis   = "synopsis"
    weight     = 6

    [[menu.main]]
    identifier = "glossary"
    name       = "Glossary"
    url        = "/glossary/"
    synopsis   = "synopsis"
    weight     = 7
