baseURL = "/"
languageCode = "en-gb"
title = "datamesh docs"

[params]
  version = "0.0.1 Alpha"

[taxonomies]
  tag = ""
  group = ""
  category = ""

[menu]
    [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

    [[menu.main]]
    identifier = "news"
    name       = "News"
    url        = "/news"
    weight     = 2
