baseURL = "/"
languageCode = "en-GB"
title = "dotmesh docs"
sectionPagesMenu = "main"

# Highlighting config (Pygments)
pygmentsCodeFences = true

pygmentsOptions = ""
# Use the Chroma stylesheet
pygmentsUseClasses = true
pygmentsUseClassic = false
pygmentsCodefencesGuessSyntax = true

# See https://help.farbox.com/pygments.html
pygmentsStyle = "monokai"

[params]
  version = "0.1"

[taxonomies]
  tag = ""
  group = ""
  category = ""

[menu]
    [[menu.main]]
    identifier = "install-setup"
    name       = "Install &amp; setup"
    url        = "/install-setup/"
    synopsis   = "Trying &amp; Installing on Docker, Kubernetes, GitLab, Jenkins &amp; Supported OSs"
    weight     = 1

    [[menu.main]]
    identifier = "concepts"
    name       = "Concepts"
    url        = "/concepts/"
    synopsis   = "What is a datadot? &amp; The architecture of dotmesh"
    weight     = 2

    [[menu.main]]
    identifier = "tasks"
    name       = "Tasks"
    url        = "/tasks/"
    synopsis   = "Using with Docker or Kubernetes, Configuration, Administration &amp; Troubleshooting"
    weight     = 3
    
    [[menu.main]]
    identifier = "tutorials"
    name       = "Tutorials"
    url        = "/tutorials/"
    synopsis   = "Detailed workflow walkthroughs"
    weight     = 4

    [[menu.main]]
    identifier = "References"
    name       = "References"
    url        = "/references/"
    synopsis   = "CLI, API, YAML references &amp; release notes"
    weight     = 5

    [[menu.main]]
    identifier = "faq"
    name       = "FAQ"
    url        = "/faq/"
    synopsis   = "Frequently asked questions"
    weight     = 6

    [[menu.main]]
    identifier = "glossary"
    name       = "Glossary"
    url        = "/glossary/"
    synopsis   = "The names of things"
    weight     = 7
