variables:
  DOCKER_API_VERSION: "1.23"
  DOCKER_REGISTRY: gcr.io
  GCP_PROJECT_ID: dotmesh-production
  GCP_ZONE: europe-west2-a
  GCP_CLUSTER_ID: production-cluster

stages:
    - build

images:
    stage: build
    tags:
        - ubuntu
        - fast
    before_script:
        - export VERSION=$(echo $CI_COMMIT_SHA | cut -c1-8)
    script:
        - make images
        - make release.build
        - bash scripts/gcloud.sh docker ps -a
        - bash scripts/gcloud.sh bash /app/pushimages.sh
