stages:
    - build

build_image:
    stage: build
    tags:
        - ubuntu
        - fast
    before_script:
        - export VERSION=$(echo $CI_COMMIT_SHA | cut -c1-8)
    script:
        - make images
        - make release.build
