variables:
  DOCKER_API_VERSION: "1.23"
  DOCKER_REGISTRY: gcr.io
  GCLOUD_PROJECT_ID: dotmesh-production
  GCLOUD_ZONE: europe-west2-a
  GCLOUD_CLUSTER_ID: production-cluster

stages:
    - build

images:
    stage: build
    tags:
        - ubuntu
        - fast
    before_script:
        - export VERSION=$(echo $CI_COMMIT_SHA | cut -c1-8)
    script:
        - make images
        - make release.build
        - bash scripts/gcloud_docker.sh kubectl get no
        - bash scripts/gcloud_docker.sh gcloud container clusters list
        #- bash scripts/gcloud_docker.sh bash /app/pushimages.sh
