stages:
    - build

build_image:
    stage: build
    before_script:
        - export VERSION=$(echo $CI_COMMIT_SHA | cut -c1-8)
        - sudo rm -f design/public
        - sudo rm -f hugo/public
    tags:
        - ubuntu
        - fast
    script:
        - make images
        - make release.build
