apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: docs-stage
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - stage.docs.dotmesh.com
    secretName: docs-stage-ingress
  rules:
  - host: stage.docs.dotmesh.com
    http:
      paths:
      - path: /
        backend:
          serviceName: docs
          servicePort: 80
